apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: dsiem-logstash
spec:
  version: 8.17.1
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: dsiem-monitoring
    logs:
      elasticsearchRefs:
        - name: dsiem-monitoring
  #  image: harbor.cdp.caas.test.btnetwork.co.uk/es-siem/logstash:8.12.2
  count: 15
  elasticsearchRefs:
    - name: dsiem
      clusterName: dsiem
  #    namespace: eck-stack
  podTemplate:
    spec:
      # OVERWRITES THE DNS NAMES OF KAFKA FROM 255. TO 253.
      hostAliases:
        - ip: "10.9.253.40"
          hostnames:
            - "tpl12719app037.iuser.iroot.adidom.com"
        - ip: "10.9.253.48"
          hostnames:
            - "tpl12719app045.iuser.iroot.adidom.com"
        - ip: "10.9.253.37"
          hostnames:
            - "tpl12719app034.iuser.iroot.adidom.com"
        - ip: "10.9.253.45"
          hostnames:
            - "tpl12719app042.iuser.iroot.adidom.com"
        - ip: "10.9.253.46"
          hostnames:
            - "tpl12719app043.iuser.iroot.adidom.com"
        - ip: "10.9.253.44"
          hostnames:
            - "tpl12719app041.iuser.iroot.adidom.com"
        - ip: "10.9.253.47"
          hostnames:
            - "tpl12719app044.iuser.iroot.adidom.com"
        - ip: "10.9.253.39"
          hostnames:
            - "tpl12719app036.iuser.iroot.adidom.com"
        - ip: "10.9.253.38"
          hostnames:
            - "tpl12719app035.iuser.iroot.adidom.com"
      #     imagePullSecrets:
      #     - name: regcred
      containers:
        - name: logstash
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms16g -Xmx16g" # Min & max heap size is set to 16gb
          #          envFrom:
          #          - secretRef:
          #              name: logstash-secrets
          volumeMounts:
            - name: pipeline-config
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: "pipelines.yml"
            - name: logstash-pipelines
              mountPath: /usr/share/logstash/pipeline/
            - name: schema-mapping
              mountPath: /usr/share/schemas/
          #            - name: truststore
          #              mountPath: /etc/logstash/ssl/truststore
          #              readOnly: true
          #            - name: keystore
          #              mountPath: /etc/logstash/ssl/keystore
          #              readOnly: true
          resources:
            requests:
              memory: 16Gi
              cpu: 4
            limits:
              memory: 16Gi
              cpu: 4
      volumes:
        - name: pipeline-config
          configMap:
            name: logstash-pipeline-config
        - name: logstash-pipelines
          configMap:
            name: logstash-pipelines
        - name: schema-mapping
          configMap:
            name: schema-mapping
  #       - name: truststore   # NEED TO GET CONNECTION REQUIREMENTS FROM KAFKA OWNERS
  #         secret:
  #           secretName: logstash-ssl-files
  #       - name: keystore
  #         secret:
  #           secretName: logstash-ssl-files
  volumeClaimTemplates:
    - metadata:
        name: logstash-data
        annotations:
          volumeType: local
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 0.1Ti
        storageClassName: local-path
  services:
    - name: api
      service:
        spec:
          type: LoadBalancer
          loadBalancerIP: 10.7.133.216
          ports:
            - port: 5044
              name: api
              protocol: TCP
              targetPort: 5044
      tls:
        certificate:
          secretName: dsiem-logstash-certs
