apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: siem
  namespace: eck-stack
spec:
  version: 8.17.2
  # monitoring:
  #   metrics:
  #     elasticsearchRefs:
  #       - name: monitoring-cluster-es
  #   logs:
  #     elasticsearchRefs:
  #       - name: monitoring-cluster-es
  nodeSets:
    - name: hot-nodes
      count: 2
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 1Gi
                  cpu: 1
                limits:
                  memory: 1Gi
                  cpu: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
