namespace: eck-stack
dataingestion_namespace: data-layer

elasticsearch:
  enabled: true
  clusterName: siem
  count: 2
  storage: 20Gi
  version: 8.17.2

kibana:
  enabled: true
  clusterName: siem
  version: 8.17.2

logstash:
  enabled: true

kafka:
  enabled: true