namespace: eck-stack

elasticsearch:
  enabled: true
  clusterName: siem
  count: 2
  storage: 20Gi
  version: 8.17.2

kibana:
  enabled: false
  clusterName: siem
  version: 8.17.2

logstash:
  enabled: false
  count: 1
  version: 8.17.2