apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.clusterName | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.version | quote }}
  nodeSets:
    - name: hot
      count: {{ .Values.count }}
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: {{ .Values.storage | quote }}
