# Cluster-level configuration
clusterName: siem
namespace: eck-stack
version: 8.17.2

# NodeSets definition (used in the "elastic-cluster.nodesets" template)
nodeSets:
  - name: hot-nodes
    count: 2
    config:
      node:
        store:
          allow_mmap: false
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 1Gi
        cpu: 1
    volumeClaim:
      accessMode: ReadWriteOnce
      size: 20Gi
